spring.application.name=elrincondelmazo

spring.config.import=optional:file:./application-secrets.properties

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
